- hosts: controlplane
  become: true
  tasks:
    - name: criando token para entrar no cluster
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - debug:
        msg: "{{ join_command_raw.stdout }}"

    - name: adicionando join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: true
  tasks:
    - name: retirar o swap
      shell: "swapoff -a"

    - name: join cluster
      shell: "sudo {{ hostvars['controlplane'].join_command }} --ignore-preflight-errors all >> node_joined.txt"
      args:
        chdir: $HOME
      register: join_worker
    
    - debug:
        msg: "{{ join_worker }}"