apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  template:
    metadata:
      name: httpd-pod
      labels: 
        app: httpd-label
    spec: 
      containers:
      - name: httpd-container
        image: httpd
        ports:
        - containerPort: 80
  replicas: 10
  selector:
    matchLabels:
      app: httpd-label